#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinhVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLySinhVien")]
	public partial class ThongTinSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void UpdateThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void DeleteThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void InsertThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void UpdateThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void DeleteThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void InsertThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void UpdateThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void DeleteThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void InsertThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    partial void UpdateThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    partial void DeleteThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    #endregion
		
		public ThongTinSVDataContext() : 
				base(global::SinhVien.Properties.Settings.Default.QuanLySinhVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongTinSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Thong_Tin_Khoa_Hoc> Thong_Tin_Khoa_Hocs
		{
			get
			{
				return this.GetTable<Thong_Tin_Khoa_Hoc>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Lien_Lac> Thong_Tin_Lien_Lacs
		{
			get
			{
				return this.GetTable<Thong_Tin_Lien_Lac>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Nguoi_LH> Thong_Tin_Nguoi_LHs
		{
			get
			{
				return this.GetTable<Thong_Tin_Nguoi_LH>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Sinh_Vien> Thong_Tin_Sinh_Viens
		{
			get
			{
				return this.GetTable<Thong_Tin_Sinh_Vien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Khoa_Hoc")]
	public partial class Thong_Tin_Khoa_Hoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _KhoaHoc;
		
		private System.DateTime _NgayNhapHoc;
		
		private string _LoaiHinhDaoTao;
		
		private string _ChuongTrinhDaoTao;
		
		private string _Khoa;
		
		private string _Nganh;
		
		private string _NienKhoa;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnKhoaHocChanging(string value);
    partial void OnKhoaHocChanged();
    partial void OnNgayNhapHocChanging(System.DateTime value);
    partial void OnNgayNhapHocChanged();
    partial void OnLoaiHinhDaoTaoChanging(string value);
    partial void OnLoaiHinhDaoTaoChanged();
    partial void OnChuongTrinhDaoTaoChanging(string value);
    partial void OnChuongTrinhDaoTaoChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    partial void OnNganhChanging(string value);
    partial void OnNganhChanged();
    partial void OnNienKhoaChanging(string value);
    partial void OnNienKhoaChanged();
    #endregion
		
		public Thong_Tin_Khoa_Hoc()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string KhoaHoc
		{
			get
			{
				return this._KhoaHoc;
			}
			set
			{
				if ((this._KhoaHoc != value))
				{
					this.OnKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._KhoaHoc = value;
					this.SendPropertyChanged("KhoaHoc");
					this.OnKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhapHoc", DbType="Date NOT NULL")]
		public System.DateTime NgayNhapHoc
		{
			get
			{
				return this._NgayNhapHoc;
			}
			set
			{
				if ((this._NgayNhapHoc != value))
				{
					this.OnNgayNhapHocChanging(value);
					this.SendPropertyChanging();
					this._NgayNhapHoc = value;
					this.SendPropertyChanged("NgayNhapHoc");
					this.OnNgayNhapHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinhDaoTao", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string LoaiHinhDaoTao
		{
			get
			{
				return this._LoaiHinhDaoTao;
			}
			set
			{
				if ((this._LoaiHinhDaoTao != value))
				{
					this.OnLoaiHinhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._LoaiHinhDaoTao = value;
					this.SendPropertyChanged("LoaiHinhDaoTao");
					this.OnLoaiHinhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuongTrinhDaoTao", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ChuongTrinhDaoTao
		{
			get
			{
				return this._ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ChuongTrinhDaoTao != value))
				{
					this.OnChuongTrinhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._ChuongTrinhDaoTao = value;
					this.SendPropertyChanged("ChuongTrinhDaoTao");
					this.OnChuongTrinhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this.OnNganhChanging(value);
					this.SendPropertyChanging();
					this._Nganh = value;
					this.SendPropertyChanged("Nganh");
					this.OnNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string NienKhoa
		{
			get
			{
				return this._NienKhoa;
			}
			set
			{
				if ((this._NienKhoa != value))
				{
					this.OnNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._NienKhoa = value;
					this.SendPropertyChanged("NienKhoa");
					this.OnNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Khoa_Hoc", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Khoa_Hoc = null;
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Khoa_Hoc = this;
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Lien_Lac")]
	public partial class Thong_Tin_Lien_Lac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _QuocGia;
		
		private string _TinhThanh;
		
		private string _QuanHuyen;
		
		private string _Phuong;
		
		private string _DiaChi;
		
		private string _DiDong;
		
		private string _Email;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    partial void OnQuanHuyenChanging(string value);
    partial void OnQuanHuyenChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDiDongChanging(string value);
    partial void OnDiDongChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Thong_Tin_Lien_Lac()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NChar(20)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NChar(20)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NChar(20)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this.OnQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._QuanHuyen = value;
					this.SendPropertyChanged("QuanHuyen");
					this.OnQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NChar(20)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiDong", DbType="NChar(20)")]
		public string DiDong
		{
			get
			{
				return this._DiDong;
			}
			set
			{
				if ((this._DiDong != value))
				{
					this.OnDiDongChanging(value);
					this.SendPropertyChanging();
					this._DiDong = value;
					this.SendPropertyChanged("DiDong");
					this.OnDiDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Lien_Lac", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Lien_Lac = null;
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Lien_Lac = this;
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Nguoi_LH")]
	public partial class Thong_Tin_Nguoi_LH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaSV;
		
		private string _HoTenLienHe;
		
		private string _DiaChiLienHe;
		
		private string _DienThoaiLienHe;
		
		private string _HoTenCha;
		
		private string _DienThoaiCha;
		
		private string _HoTenMe;
		
		private string _DienThoaiMe;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenLienHeChanging(string value);
    partial void OnHoTenLienHeChanged();
    partial void OnDiaChiLienHeChanging(string value);
    partial void OnDiaChiLienHeChanged();
    partial void OnDienThoaiLienHeChanging(string value);
    partial void OnDienThoaiLienHeChanged();
    partial void OnHoTenChaChanging(string value);
    partial void OnHoTenChaChanged();
    partial void OnDienThoaiChaChanging(string value);
    partial void OnDienThoaiChaChanged();
    partial void OnHoTenMeChanging(string value);
    partial void OnHoTenMeChanged();
    partial void OnDienThoaiMeChanging(string value);
    partial void OnDienThoaiMeChanged();
    #endregion
		
		public Thong_Tin_Nguoi_LH()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenLienHe", DbType="NChar(10)")]
		public string HoTenLienHe
		{
			get
			{
				return this._HoTenLienHe;
			}
			set
			{
				if ((this._HoTenLienHe != value))
				{
					this.OnHoTenLienHeChanging(value);
					this.SendPropertyChanging();
					this._HoTenLienHe = value;
					this.SendPropertyChanged("HoTenLienHe");
					this.OnHoTenLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiLienHe", DbType="NChar(10)")]
		public string DiaChiLienHe
		{
			get
			{
				return this._DiaChiLienHe;
			}
			set
			{
				if ((this._DiaChiLienHe != value))
				{
					this.OnDiaChiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DiaChiLienHe = value;
					this.SendPropertyChanged("DiaChiLienHe");
					this.OnDiaChiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiLienHe", DbType="NChar(10)")]
		public string DienThoaiLienHe
		{
			get
			{
				return this._DienThoaiLienHe;
			}
			set
			{
				if ((this._DienThoaiLienHe != value))
				{
					this.OnDienThoaiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiLienHe = value;
					this.SendPropertyChanged("DienThoaiLienHe");
					this.OnDienThoaiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenCha", DbType="NChar(10)")]
		public string HoTenCha
		{
			get
			{
				return this._HoTenCha;
			}
			set
			{
				if ((this._HoTenCha != value))
				{
					this.OnHoTenChaChanging(value);
					this.SendPropertyChanging();
					this._HoTenCha = value;
					this.SendPropertyChanged("HoTenCha");
					this.OnHoTenChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiCha", DbType="NChar(20)")]
		public string DienThoaiCha
		{
			get
			{
				return this._DienThoaiCha;
			}
			set
			{
				if ((this._DienThoaiCha != value))
				{
					this.OnDienThoaiChaChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiCha = value;
					this.SendPropertyChanged("DienThoaiCha");
					this.OnDienThoaiChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenMe", DbType="NChar(10)")]
		public string HoTenMe
		{
			get
			{
				return this._HoTenMe;
			}
			set
			{
				if ((this._HoTenMe != value))
				{
					this.OnHoTenMeChanging(value);
					this.SendPropertyChanging();
					this._HoTenMe = value;
					this.SendPropertyChanged("HoTenMe");
					this.OnHoTenMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiMe", DbType="NChar(20)")]
		public string DienThoaiMe
		{
			get
			{
				return this._DienThoaiMe;
			}
			set
			{
				if ((this._DienThoaiMe != value))
				{
					this.OnDienThoaiMeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiMe = value;
					this.SendPropertyChanged("DienThoaiMe");
					this.OnDienThoaiMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Nguoi_LH", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Nguoi_LHs.Remove(this);
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Nguoi_LHs.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Sinh_Vien")]
	public partial class Thong_Tin_Sinh_Vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _NoiSinh;
		
		private string _GioiTinh;
		
		private string _CCCD;
		
		private string _DanToc;
		
		private string _LopSV;
		
		private System.Data.Linq.Binary _Photo;
		
		private EntityRef<Thong_Tin_Khoa_Hoc> _Thong_Tin_Khoa_Hoc;
		
		private EntityRef<Thong_Tin_Lien_Lac> _Thong_Tin_Lien_Lac;
		
		private EntitySet<Thong_Tin_Nguoi_LH> _Thong_Tin_Nguoi_LHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnLopSVChanging(string value);
    partial void OnLopSVChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    #endregion
		
		public Thong_Tin_Sinh_Vien()
		{
			this._Thong_Tin_Khoa_Hoc = default(EntityRef<Thong_Tin_Khoa_Hoc>);
			this._Thong_Tin_Lien_Lac = default(EntityRef<Thong_Tin_Lien_Lac>);
			this._Thong_Tin_Nguoi_LHs = new EntitySet<Thong_Tin_Nguoi_LH>(new Action<Thong_Tin_Nguoi_LH>(this.attach_Thong_Tin_Nguoi_LHs), new Action<Thong_Tin_Nguoi_LH>(this.detach_Thong_Tin_Nguoi_LHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopSV", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string LopSV
		{
			get
			{
				return this._LopSV;
			}
			set
			{
				if ((this._LopSV != value))
				{
					this.OnLopSVChanging(value);
					this.SendPropertyChanging();
					this._LopSV = value;
					this.SendPropertyChanged("LopSV");
					this.OnLopSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Khoa_Hoc", Storage="_Thong_Tin_Khoa_Hoc", ThisKey="MaSV", OtherKey="MaSV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Khoa_Hoc Thong_Tin_Khoa_Hoc
		{
			get
			{
				return this._Thong_Tin_Khoa_Hoc.Entity;
			}
			set
			{
				Thong_Tin_Khoa_Hoc previousValue = this._Thong_Tin_Khoa_Hoc.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Khoa_Hoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Khoa_Hoc.Entity = null;
						previousValue.Thong_Tin_Sinh_Vien = null;
					}
					this._Thong_Tin_Khoa_Hoc.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Sinh_Vien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Khoa_Hoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Lien_Lac", Storage="_Thong_Tin_Lien_Lac", ThisKey="MaSV", OtherKey="MaSV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Lien_Lac Thong_Tin_Lien_Lac
		{
			get
			{
				return this._Thong_Tin_Lien_Lac.Entity;
			}
			set
			{
				Thong_Tin_Lien_Lac previousValue = this._Thong_Tin_Lien_Lac.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Lien_Lac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Lien_Lac.Entity = null;
						previousValue.Thong_Tin_Sinh_Vien = null;
					}
					this._Thong_Tin_Lien_Lac.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Sinh_Vien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Lien_Lac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Nguoi_LH", Storage="_Thong_Tin_Nguoi_LHs", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<Thong_Tin_Nguoi_LH> Thong_Tin_Nguoi_LHs
		{
			get
			{
				return this._Thong_Tin_Nguoi_LHs;
			}
			set
			{
				this._Thong_Tin_Nguoi_LHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thong_Tin_Nguoi_LHs(Thong_Tin_Nguoi_LH entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = this;
		}
		
		private void detach_Thong_Tin_Nguoi_LHs(Thong_Tin_Nguoi_LH entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = null;
		}
	}
}
#pragma warning restore 1591
